AWSTemplateFormatVersion: 2010-09-09
Description: IAM Stack

Resources:
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3Access
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - s3:*
          Resource: '*'
      Roles:
      - Ref: AppRole
  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: AppRole
Outputs:
  AppInstanceProfile:
    Description: Application EC2 Instance Profile 
    Value: !Ref AppInstanceProfile
    Export:  
      Name: !Sub ${AWS::StackName}-AppInstanceProfile
